apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sa
      containers:
        - name: telemetry
          image: axionacr2029.azurecr.io/telemetry:v1
          ports:
            - containerPort: 8000
          envFrom:
          - configMapRef:
              name: telemetry-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: telemetry-secrets
                  key: DATABASE_URL
          volumeMounts:
          - name: telemetry-secrets
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
          - name: telemetry-secrets
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: telemetry-kv
          
