apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: telemetry-kv
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: telemetry-secrets
      type: Opaque
      data:
        - objectName: telemetry-database-url
          key: DATABASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "61af4870-b0c0-4c30-b8a5-61b3dcc66486"
    keyvaultName: "azrkeyvault-axion-2026"
    tenantId: "f8163445-6c70-454f-8963-bfc99239ca72"
    objects: |
      array:
        - |
          objectName: telemetry-database-url
          objectType: secret
