apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
  PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
  PGADMIN_DEFAULT_EMAIL: "user@admin.com"