apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sa
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-credentials
                  key: PGADMIN_DEFAULT_PASSWORD
          volumeMounts:
            - name: pgadmin-secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: pgadmin-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: pgadmin-kv