apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgadmin-kv
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: pgadmin-credentials
      type: Opaque
      data:
        - objectName: pgadmin-email
          key: PGADMIN_DEFAULT_EMAIL
        - objectName: pgadmin-password
          key: PGADMIN_DEFAULT_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "61af4870-b0c0-4c30-b8a5-61b3dcc66486"
    keyvaultName: "azrkeyvault-axion-2026"
    tenantId: "f8163445-6c70-454f-8963-bfc99239ca72"
    objects: |
      array:
        - |
          objectName: pgadmin-email
          objectType: secret
        - |
          objectName: pgadmin-password
          objectType: secret