apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: ClusterIP  # Public IP generate karega browser access ke liye
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pgadmin