apiVersion: apps/v1
kind:   Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ingestion
  template:
    metadata: 
      labels:
        app: ingestion
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sa
      containers:
        - name: ingestion
          image: axionacr2029.azurecr.io/ingestion:v1
          ports:
          - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ingestion-secrets
                  key: DATABASE_URL
          volumeMounts:
          - name: ingestion-secrets
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: ingestion-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ingestion-kv
      
      

      
