apiVersion: apps/v1
kind: Deployment
metadata:
  name: axionui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
      - name: axionui
        image: axionacr2029.azurecr.io/axionui:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: axionui-config
