apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: axionui-kv
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: axionui-credentials
      type: Opaque
      data:
        - objectName: postgres-user
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "fa6c6cbb-e0f4-48e0-857f-537bf2a53046"
    keyvaultName: "azrkeyvault-axion-2026"
    tenantId: "f8163445-6c70-454f-8963-bfc99239ca72"
    objects: |
      array:
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
