apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-kv
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: postgres-credentials
      type: Opaque
      data:
        - objectName: postgres-user
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
        - objectName: postgres-db
          key: POSTGRES_DB
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "61af4870-b0c0-4c30-b8a5-61b3dcc66486"
    keyvaultName: "azrkeyvault-axion-2026"
    tenantId: "f8163445-6c70-454f-8963-bfc99239ca72"
    objects: |
      array:
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-db
          objectType: secret